# Generated by Django 5.1.2 on 2024-12-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_person_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='Bangalore', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='India', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='fathername',
            field=models.CharField(default='Papa', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='jee_marks',
            field=models.IntegerField(default=202),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='mothername',
            field=models.CharField(default='Mommy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(default='West Bengal', max_length=25),
            preserve_default=False,
        ),
    ]
