# Generated by Django 5.1.2 on 2024-12-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_person_city_person_country_person_fathername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=25)),
                ('mothername', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('jee_marks', models.IntegerField()),
                ('country', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
    ]
