# Generated by Django 5.1.2 on 2024-12-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_adm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=25)),
                ('mothername', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('jee_marks', models.IntegerField()),
                ('country', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'admission_stud_adm',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='student',
            name='mothername',
            field=models.CharField(max_length=25),
        ),
    ]
