# Generated by Django 5.1.2 on 2024-12-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_stud_adm_remove_student_password_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stud_adm',
            table='stud_adm',
        ),
    ]
