# Generated by Django 5.1.2 on 2024-12-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_alter_stud_adm_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stud_adm',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
